server:
  port: 8080
  servlet:
    context-path: /re
spring:
  profiles:
    active: dev
  # 配置文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


jwt:
  # 配置jwt过期时间 单位 小时
  expire: 2
  # 配置jwt秘钥
  secretKey: ROOTELEMENT

rest:
  readTimeout: 100
  connectTimeout: 100

mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl