spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://192.168.1.10:8003/re?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: re#mysql2020
  # 配置redis
  redis:
    port: 8004
    host: 192.168.1.10
    password: re#redis2020

logging:
  level:
    root: info
    cn.ljtnono.re.api: info
# 配置logging等级