server:
  port: 8080
  servlet:
    context-path: /re
spring:
  profiles:
    active: dev
  # 配置文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  expire: 7200000
  secretKey: ROOTELEMENT

mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: cn.ljtnono.re.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl