server:
  port: 8001
  servlet:
    context-path: /re
# spring 相关设置
spring:
  profiles:
    active: @profiles.active@
  # 配置utf-8编码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# rest
rest:
  read-timeout: 100
  connect-timeout: 100

# mybatis-plus 配置
mybatis-plus:
  global-config:
    banner: false
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志配置
logging:
  config: classpath:log/logback-${spring.profiles.active}.xml
  level: info